#Francisco Juaquin Murcia Gomez 48734281H
OPTS = -Wall -O3 -std=c++11

maxsum-greedy: maxsum-bt.cc
	g++ ${OPTS} -o maxsum-bt maxsum-bt.cc	 

tar: maxsum-bt.cc  makefile
	tar cvfz 48734281H.tar.gz maxsum-bt.cc makefile
