COMP	= mpicc
OPT     = -O3 -w

all: ejemplo1 ejemplo2 ejemplo3 ejemplo4 ejemplo5 ejemplo6 ejemplo7 ejemplo8 ejemplo10 ejemplo11 ejemplo12 ejemplo13 ejemplo14 pi ejemplo_pool psdot

ejemplo1: ejemplo1.c
	$(COMP)  $(OPT)  -o $@ $@.c 
ejemplo2: ejemplo2.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo3: ejemplo3.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo4: ejemplo4.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo5: ejemplo5.c 
	$(COMP)  $(OPT)  -o $@ $@.c 
ejemplo6: ejemplo6.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo7: ejemplo7.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo8: ejemplo8.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo10: ejemplo10.c 
	$(COMP)  $(OPT)  -o $@ $@.c 
ejemplo11: ejemplo11.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo12: ejemplo12.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo13: ejemplo13.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo14: ejemplo14.c
	$(COMP)  $(OPT)  -o $@ $@.c
ejemplo_pool: ejemplo_pool.c
	$(COMP)  $(OPT)  -o $@ $@.c
pi: pi.c
	$(COMP)  $(OPT)  -o $@ $@.c 
psdot: psdot.c
	$(COMP)  $(OPT)  -o $@ $@.c 

reset:
	rm ejemplo1 ejemplo2 ejemplo3 ejemplo4 ejemplo5 ejemplo6 ejemplo7 ejemplo8 ejemplo10 ejemplo11 ejemplo12 ejemplo13 ejemplo14 pi ejemplo_pool psdot

