#Francisco Juaquin Murcia Gomez 48734281H
OPTS = -Wall -O3 -std=c++0x

maxsum-greedy: maxsum-greedy.cc
	g++ ${OPTS} -o maxsum-greedy maxsum-greedy.cc	 

tar: maxsum-greedy.cc  makefile
	tar cvfz 48734281H.tar.gz maxsum-greedy.cc makefile
